version: '3'
services:
  db:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
  web:
    build: .
    command: rake db:create
    command: rake db:migrate
    command:
      - rake event_collector:events_generator
      - rake event_collector:users_generator
      - rake event_collector:tickets_generator

    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3010 -b '0.0.0.0'"
    volumes:
      - .:/myapp
    ports:
      - "3010:3010"
    depends_on:
      - db
      - redis
  redis:
    image: 'redis:4.0-alpine'
    command: redis-server
    expose: 
     - 6379

  sidekiq:
    depends_on:
        - 'db'
        - 'redis'
    build: .
    command: sidekiq
    volumes:
        - '.:/app'
    env_file:
        - '.env'